import "./globals.css";
import NavigationBar from "./components/NavigationBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <NavigationBar /> */}
      <body>
        <NavigationBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
